version: '3.8'

services:
    mysql:
        container_name: mysql
        image: mysql:8.0
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: knp-taste
        logging:
            driver: "json-file"
            options:
                max-size: 10m
                max-file: "14"

    adminer:
        container_name: adminer
        image: adminer
        restart: on-failure
        ports:
            - '8080:8080'
        logging:
            driver: "json-file"
            options:
                max-size: 10m
                max-file: "14"

    nginx:
        container_name: nginx
        image: nginx:1.19.0-alpine
        restart: on-failure
        volumes:
            - './apps/knp-taste/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '80:80'
        depends_on:
            - php
        logging:
            driver: "json-file"
            options:
                max-size: 10m
                max-file: "14"

    php:
        container_name: php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - './apps/knp-taste/:/usr/src/app'
        restart: on-failure
        env_file:
            - .env
        user: 1000:1000
        logging:
            driver: "json-file"
            options:
                max-size: 10m
                max-file: "14"

